class PlaceValidator < ActiveModel::Validator
  def validate(record)
    if record.lat.blank?
      record.errors[:place] << 'unrecognized'
    end
  end
end
class Property < ApplicationRecord
  attr_accessor :place
  has_one_attached :img1
  has_one_attached :img2
  has_one_attached :img3
  has_one_attached :img4

  belongs_to :user
  has_and_belongs_to_many :users

  #validates :img1, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  validates_each(:acre, :cent, :expected_price, :landmark) do |record, attr, value|
    if value.blank?
      record.errors.add(attr, 'must be given')
    end
  end


  reverse_geocoded_by :lat, :lngt
  before_validation :set_coordinates
  def set_coordinates
    result = Geocoder.search(self.place)
    if result.first.present?
      coordinates = result.first.coordinates
      self.lat = coordinates[0]
      self.lngt = coordinates[1]
    end
  end

  validates_with PlaceValidator

  def self.search(state, price_range, acre_range, coordinates)
    sql = Property
    sql = sql.where(state: state)
    sql = sql.where(expected_price: price_range)
    sql = sql.where(land_mass: acre_range)
    if coordinates.present?
      sql = sql.near(coordinates, 50)
    end
    sql
  end

  before_save :calculate_land_mass
  def calculate_land_mass
    self.land_mass = "#{acre}.#{cent}".to_f
  end

  PLACES = %w{
    Karadukka
    Manjeshwaram
    Kasaragod
    Kanhangad
    Parappa
    Neeleshwaram
    Kumbadaje
    Bellore
    Karadka
    Muliyar
    Delampady
    Bedadka
    Kuttikol
    Manjeswaram
    Vorkady
    Meenja
    Mangalpady
    Paivalige
    Puthige
    Enmakaje
    Kumbala
    Badiadka
    Mogral Puthur
    Madhur
    Chemnad
    Chengala
    Udma
    Pallikara
    Ajanur
    Pullur Periya
    Madikai
    Kodom Belur
    Kallar
    Panathady
    Balal
    Kinanur karinthalam
    West Eleri
    East Eleri
    Kayyur cheemeni
    Cheruvathur
    Valiyaparamba
    Padne
    Pilicode
    Thrikaripur
    Koothuparambu
    Peravoor
    Panoor
    Edakkad
    Erikoor
    Payyannur
    Kalyasseri
    Thaliparambu
    Kannur
    Iritty
    Thalassery
    Kunjimangalam
    Ramanthali
    Kankol - Alappadambu
    Karivellur - Peralam
    Eramom - Kuttoor
    Peringom - Vayakkara
    Cherupuzha
    Cheruthazham
    Ezhom
    Madayi
    Mattool
    Cherukunnu
    Kalyasseri
    Kannapuram
    Narath
    Pattuvom
    Chengalayi
    Kurumathur
    Pariyaram
    Chapparapadavu
    Naduvil
    Udayagiri
    Alakkode
    Kadannappally - Panappuzha
    Erikoor
    Eruvessi
    Malappattam
    Payyavur
    Kuttiyatoor
    Mayyil
    Padiyoor
    Ulickal
    Pappinissery
    Chirakkal
    Valapatanam
    Azheekode
    Kolacheri
    Kadampur
    Chempilode
    Munderi
    Peralassery
    Anjarakandi
    Muzhuppilangad
    Dharmadam
    Eranjoli
    Pinarayi
    New Mahee
    Vengad
    Kottayam
    Thruppangottur
    Chittariparambu
    Kunnothuparambu
    Mangattidam
    Pattiyam
    Kathiroor
    Chokli
    Mokeri
    Panniyannur
    Aaralam
    Ayyankunnu
    Keezhallur
    Thillankeri
    Koodali
    Payam
    Kanichar
    Kelakam
    Kottiyoor
    Muzhakkunnu
    Kolayad
    Maloo
    Peravur
    Sulthan Betheri
    Mananthavadi
    Kalpatta
    Panamaram
    Vellamunda
    Thirunelli
    Thondernad
    Edavaka
    Thavinhal
    Nenmeni
    Noolpuzha
    Ambalavayal
    Meenangadi
    Vengapally
    Pozhuthana
    Vythiri
    Thariyode
    Meppadi
    Muppainad
    Kottathara
    Muttil
    Padinjarathara
    Panamaram
    Kaniyampatta
    Poothadi
    Pulppalli
    Mullankolly
    Vatakara
    Thuneri
    Kunnummal
    Thodannur
    Melady
    Perambra
    Balussery
    Koduvally
    Panthalayani
    Chelannur
    Kunnamangalam
    Kozhikode
    Azhiyur
    Chorode
    Eramala
    Onchiyam
    Chekiad
    Purameri
    Thuneri
    Valayam
    Vanimel
    Edacheri
    Nadapuram
    Kunnummal
    Velom
    Kayakkodi
    Kavilumpara
    Kuttiadi
    Maruthonkara
    Narippatta
    Ayancheri
    Villiappally
    Maniyur
    Thiruvallur
    Thurayur
    Keezhariyur
    Thikkodi
    Meppayur
    Cheruvannur
    Nochad
    Changaroth
    Kayanna
    Koothali
    Perambra
    Chakkittappara
    Balussery
    Naduvannur
    Kottur
    Ulliyeri
    Unnikulam
    Panangad
    Koorachundu
    Chemancheri
    Arikkulam
    Moodadi
    Chengottukavu
    Atholi
    Kakkodi
    Chelannur
    Kakkur
    Nanmanda
    Narikkuni
    Thalakkulathur
    Thiruvambadi
    Koodaranhi
    Kizhakkoth
    Madavoor
    Puthuppadi
    Thamarassery
    Omassery
    Kattippara
    Kodancherry
    Kodiyathur
    Kuruvattur
    Mavoor
    Karassery
    Kunnamangalam
    Chathamangalam
    Peruvayal
    Perumanna
    Kadalundi
    Olavanna
    Nilambur
    Kondotty
    Wandoor
    Kalikkavu
    Areecode
    Malappuram
    Perinthalmanna
    Mankada
    Kuttipuram
    Tanur
    Tirur
    Vengara
    Tirurangadi
    Ponnani
    Perumpadappu
    Vazhikkadavu
    Pothukal
    Edakkara
    Moothedam
    Chunkathara
    Chaliyar
    Cherukavu
    Pallikkal
    Vazhayur
    Vazhakkad
    Pulickal
    Muthuvallur
    Chelembra
    Wandoor
    Thiruvali
    Mampad
    Poroor
    Pandikkad
    Thrikkalangode
    Kalikkavu
    Chokkad
    Karuvarakundu
    Thuvoor
    Amarambalam
    Karulayi
    Edapatta
    Areecode
    Oorngattiri
    Kavanur
    Keezhuparambu
    Kuzhimanna
    Cheekode
    Pulpatta
    Edavanna
    Anakkayam
    Morayur
    Ponmala
    Pookottur
    Othukkungal
    Kodur
    Aliparambu
    Elamkulam
    Melattur
    Keezhattur
    Thazhekkad
    Vettathur
    Pulamanthole
    Angadipuram
    Kuruva
    Koottilangadi
    Puzhakkatiri
    Moorkkanad
    Makkaraparambu
    Mankada
    Athavanad
    Edayur
    Irumbiliyam
    Marakkara
    Kuttipuram
    Kalpakancheri
    Ponmundam
    Cheriyamundam
    Ozhur
    Niramaruthur
    Thanaloor
    Valavanoor
    Perumanna Clari
    A.R. Nagar
    Parappur
    Thennala
    Vengara
    Kannamangalam
    Oorakam
    Edarikode
    Nannambra
    Munniyoor
    Thenjipalam
    Vallikunnu
    Peruvallur
    Purathur
    Mangalam
    Thrippangode
    Vettom
    Thalakkad
    Thirunavaya
    Thavanoor
    Vattamkulam
    Edappal
    Kaladi
    Alangode
    Maranjeri
    Nannamukku
    Perumpadappu
    Veliyangode
    Thrithala
    Pattambi
    Ottappalam
    Sreekrishnapuram
    Mannarkkad
    Attapadi
    Palakkad
    Kuzhalmandam
    Chittoor
    Kollengode
    Nenmara
    Malampuzha
    Alathur
    Anakkara
    Chalisseri
    Kappur
    Nagalassery
    Pattithara
    Thirumittakkode
    Thrithala
    Koppam
    Kulukkallur
    Muthuthala
    Ongallur
    Thiruvegapppura
    Vilayoor
    Paruthoor
    Ambalappara
    Ananganadi
    Chalavara
    Lekkidi Peroor
    Vaniyamkulam
    Thrukkadeeri
    Vallappuzha
    Nellaya
    Kadmpazhipuram
    Karimpuzha
    Sreekrishnapuram
    Vellinezhi
    Karakurissi
    Thachanattukara
    Pookottukavu
    Alanallur
    Karimpa
    Kottopadam
    Kumaramputhur
    Kanjirapuzha
    Thachampara
    Thenkara
    Agali
    Puthoor
    Sholayoor
    Pirayiri
    Mundoor
    Kongad
    Keralassery
    Mannur
    Mankara
    Parali
    Kottayi
    Kuthanoor
    Kuzhalmannam
    Mathoor
    Peringottukurissi
    Thenkurissi
    Kannadi
    Eruthempathi
    Kozhinjampara
    Nalleppilly
    Perumatty
    Vadakarapathy
    Elappulli
    Polppulli
    Kollamkode
    Koduvayur
    Muthalamada
    Puthunagaram
    Vatavannur
    Peruvempu
    Pattancheri
    Ayiloor
    Nelliyampathy
    Elavancheri
    Pallassena
    Melarkode
    Nenmara
    Vandazhi
    Akathethara
    Malampuzha
    Marutha Road
    Puthupariyaram
    Puthussery
    Kodumpu
    Alathur
    Erimayur
    Kavassery
    Kizhakkanchery
    Puthukkode
    Tharoor
    Vadakkanchery
    Kannambra
    Anakkara
    Chalisseri
    Kappur
    Nagalassery
    Pattithara
    Thirumittakkode
    Thrithala
    Koppam
    Kulukkallur
    Muthuthala
    Ongallur
    Thiruvegapppura
    Vilayoor
    Paruthoor
    Ambalappara
    Ananganadi
    Chalavara
    Lekkidi Peroor
    Vaniyamkulam
    Thrukkadeeri
    Vallappuzha
    Nellaya
    Kadmpazhipuram
    Karimpuzha
    Sreekrishnapuram
    Vellinezhi
    Karakurissi
    Thachanattukara
    Pookottukavu
    Alanallur
    Karimpa
    Kottopadam
    Kumaramputhur
    Kanjirapuzha
    Thachampara
    Thenkara
    Agali
    Puthoor
    Sholayoor
    Pirayiri
    Mundoor
    Kongad
    Keralassery
    Mannur
    Mankara
    Parali
    Kottayi
    Kuthanoor
    Kuzhalmannam
    Mathoor
    Peringottukurissi
    Thenkurissi
    Kannadi
    Eruthempathi
    Kozhinjampara
    Nalleppilly
    Perumatty
    Vadakarapathy
    Elappulli
    Polppulli
    Kollamkode
    Koduvayur
    Muthalamada
    Puthunagaram
    Vatavannur
    Peruvempu
    Pattancheri
    Ayiloor
    Nelliyampathy
    Elavancheri
    Pallassena
    Melarkode
    Nenmara
    Vandazhi
    Akathethara
    Malampuzha
    Marutha Road
    Puthupariyaram
    Puthussery
    Kodumpu
    Alathur
    Erimayur
    Kavassery
    Kizhakkanchery
    Puthukkode
    Tharoor
    Vadakkanchery
    Kannambra
    Kadappuram
    Orumanayur
    Punnayur
    Punnayurkulam
    Vadakkekad
    Choondal
    Chowannur
    Kadavallur
    Kandanassery
    Kattakampal
    Porkulam
    Kadangode
    Velur
    Desamangalam
    Erumapetty
    Mulloorkara
    Thekkumkara
    Varavoor
    Chelakkara
    Vallathol Nagar
    Kondazhy
    Panjal
    Pazhayannur
    Thiruvilwamala
    Madakkathara
    Nadathara
    Pananchery
    Puthur
    Adat
    Avanoor
    Kaiparambu
    Mulamkunnathukavu
    Tholur
    Kolazhy
    Elavally
    Mullassery
    Pavaratty
    Venkidangu
    Engandiyur
    Vadanappilly
    Thalikulam
    Nattika
    Valappad
    Edathiruthy
    Kaipamangalam
    Mathilakam
    Perinjanam
    Sreenarayanapuram
    Edavilangu
    Eriyad
    Anthikad
    Thanniam
    Chazhoor
    Manalur
    Arimbur
    Avinissery
    Cherpu
    Paralam
    Vallachira
    Alagapanagar
    Kodakara
    Mattathur
    Nenmanikkara
    Pudukkad
    Thrikkur
    Varantharappilly
    Karalam
    Kattur
    Muriyad
    Parappukkara
    Padiyur
    Poomangalam
    Puthenchira
    Vellangallur
    Velukkara
    Aloor
    Annamanada
    Kuzhur
    Mala
    Poyya
    Kadukutty
    Kodadssery
    Koratty
    Melur
    Pariyaram
    Athirappilly
    Alangad
    Angamaly
    Edappally
    Koovappady
    Kothamangalam
    Mulanthuruthy
    Muvattupuzha
    Palluruthy
    Pampakuda
    Parakkadavu
    Paravur
    Vadavucode
    Vazhakulam
    Vypin
    Adimaly
    Alakode 
    Arakulam 
    AyyappanCoil
    BysonValley
    Chakkupallam 
    Chinnakanal
    Devikulam
    Edamalakkudy
    Edavetty
    Kamakshy
    Kanchiyar
    Kanthalloor
    Karimannoor
    Karimkunnam
    Karunapuram
    Kodikulam
    Kokkayar 
    Konnathady 
    Kudayathoor 
    Kumaramangalam 
    Kumily 
    Manakkad 
    Mankulam 
    Marayoor 
    Mariyapuram 
    Munnar 
    Muttom 
    Nedumkandam 
    Pallivasal 
    Pampadumpara 
    Peermade 
    Peruvanthanam 
    Purapuzha 
    Rajakkad 
    Rajakumary 
    Santhanpara
    Senapathy 
    Udumbanchola 
    Udumbanoor 
    Upputhara 
    Vandanmedu 
    Vandiperiyar 
    Vannappuram 
    Vathikudy 
    Vattavada 
    Vazhathope 
    Vellathooval 
    Velliyamattom 
    Akalakunnam 
    Arpookara 
    Athirampuzha 
    Ayarkunnam 
    Aymanam 
    Bharananganam 
    Chempu 
    Chirakkadavu 
    Elikulam 
    Erumely 
    Kadanad 
    Kadaplamattom 
    Kaduthuruthy 
    Kallara 
    Kanakkary 
    Kangazha 
    Kanjirappally 
    Karoor 
    Karukachal 
    Kidangoor 
    Kooroppada 
    Koottickal 
    Koruthodu 
    Kozhuvanal 
    Kumarakom 
    Kuravilangad 
    Kurichy 
    Madappally 
    Manarcadu 
    Manimala 
    Manjoor 
    Marangattupilly 
    Maravanthuruthu 
    Meenachil 
    Meenadom 
    Melukavu 
    Moonnilavu 
    Mulakulam 
    Mundakayam 
    Mutholy 
    Nedumkunnam 
    Neendoor 
    Neezhoor 
    Paippad 
    Pallickathodu 
    Pampady 
    Panachikkad 
    Parathodu 
    Poonjar 
    Poonjar Thekkekara 
    Puthuppally 
    Ramapuram 
    Teekoy 
    Thalanad 
    Thalappalam 
    Thalayazham 
    Thalayolaparambu 
    Thidanad 
    Thiruvarppu 
    Thrickodithanam 
    TV Puram 
    Udayanapuram 
    Uzhavoor 
    Vakathanam 
    Vazhappally 
    Vazhoor 
    Vechoor 
    Veliyannoor 
    Vellavoor 
    Velloor 
    Vijayapuram 
    Ala 
    Ambalapuzha North 
    Ambalapuzha South 
    Arattupuzha 
    Arookutty 
    Aroor 
    Aryad 
    Bharanickavu 
    Budhanoor 
    Champakulam 
    Chennam Pallippuram 
    Chennithala-Thripperumthura 
    Cheppad 
    Cheriyanad 
    Cherthala South 
    Cheruthana 
    Chettikulangara 
    Chingoli 
    Chunakara 
    Devikulangara 
    Edathua 
    Ezhupunna 
    Kadakkarappally 
    Kainakary 
    Kandalloor 
    Kanjikuzhy 
    Karthikappally 
    Karuvatta 
    Kavalam 
    Kodamthuruth 
    Krishnapuram 
    Kumarapuram 
    Kuthiathod 
    Mannancherry 
    Mannar 
    Mararikulam North 
    Mararikulam South 
    Mavelikara Thamarakulam 
    Mavelikara Thekkekara 
    Muhamma 
    Mulakuzha 
    Muthukulam 
    Muttar 
    Nedumudi 
    Neelamperoor 
    Nooranad 
    Palamel 
    Pallippad 
    Panavally 
    Pandanad 
    Pathiyoor 
    Pattanakkad 
    Perumpalam 
    Pulincunnoo 
    Puliyoor 
    Punnapra North 
    Punnapra South 
    Purakkad 
    Ramankary 
    Thakazhy 
    Thalavady 
    Thanneermukkom 
    Thazhakara 
    Thiruvanvandoor 
    Thrikkunnappuzha 
    Thuravoor 
    Thycattussery 
    Vallikunnam 
    Vayalar 
    Veeyapuram 
    Veliyanad 
    Venmoney 
    Anicadu 
    Aranmula 
    Aruvappulam 
    Ayroor 
    Chenneerkara 
    Cherukole 
    Chittar 
    Erathu 
    Enadimangalam 
    Eraviperoor 
    Ezhamkulam 
    Ezhumattoor 
    Kadampanad 
    Kadapra 
    Kalanjoor 
    Kallooppara 
    Kaviyoor 
    Kodumon 
    Koipuram 
    Konni 
    Kottanad 
    Kottangal 
    Kozhencherry 
    Kulanada 
    Kunnamthanam 
    Kuttoor 
    Malayalapuzha 
    Mallappally 
    Mallappuzhassery 
    Mezhuveli 
    Mylapra 
    Naranammoozhy 
    Naranganam 
    Nedumpuram 
    Niranam 
    Omalloor 
    Pallickal 
    Pandalam Thekkekara 
    Peringara 
    Pramadom 
    Puramattom 
    Ranni Angadi 
    Ranni 
    Ranni Pazhavangadi 
    Ranni Perunadu 
    Seethathodu 
    Thannithodu 
    Thottappuzhassery 
    Thumpamon 
    Vadaserikara 
    Vallicode 
    Vechoochira 
    Adichanalloor 
    Alappad 
    Alayamon 
    Anchal 
    Aryankavu 
    Chadayamangalam 
    Chathannoor 
    Chavara 
    Chirakkara 
    Chithara 
    Clappana 
    East Kallada 
    Edamulackal 
    Elamadu 
    Elampalloor 
    Ezhukone 
    Ittiva 
    Kadakkal 
    Kalluvathukkal 
    Karavaloor 
    Kareepra 
    Kottamkara 
    Kulakkada 
    Kulasekharapuram 
    Kulathupuzha 
    Kummil 
    Kundara 
    Kunnathoor 
    Mayyanad 
    Melila 
    Munroethuruth 
    Mylom 
    Mynagappally 
    Nedumpana 
    Neduvathoor 
    Neendakara 
    Nilamel 
    Oachira 
    Panayam 
    Panmana 
    Pathanapuram 
    Pattazhi 
    Pattazhi Vadakkekara 
    Pavithreswaram 
    Perayam 
    Perinad 
    Piravanthoor 
    Poothakulam 
    Pooyappally 
    Poruvazhy 
    Sasthamcotta 
    Sooranad North 
    Sooranad South 
    Thalavoor 
    Thazhava 
    Thekkumbhagom 
    Thenmala 
    Thevalakkara 
    Thodiyoor 
    Thrikkaruva 
    Thrikkovilvattom 
    Ummannoor 
    Velinalloor 
    Veliyam 
    Vettikavala 
    Vilakkudy 
    West Kallada 
    Yeroor 
    Amboori 
    Anad 
    Anchuthengu 
    Andoorkonam 
    Aruvikkara 
    Aryanad 
    Aryancode 
    Athiyannoor 
    Azhoor 
    Balaramapuram 
    Chemmaruthy 
    Chenkal 
    Cherunniyoor 
    Chirayinkeezhu 
    Edava 
    Elakamon 
    Kadakkavoor 
    Kadinamkulam 
    Kallara 
    Kallikkadu 
    Kalliyoor 
    Kanjiramkulam 
    Karakulam 
    Karavaram 
    Karode 
    Karumkulam 
    Kattakada 
    Kilimanoor 
    Kizhuvilam 
    Kollayil 
    Kottukal 
    Kulathoor 
    Kunnathukal 
    Kuttichal 
    Madavoor 
    Malayinkeezh 
    Manamboor 
    Mangalapuram 
    Manickal 
    Maranalloor 
    Mudakkal 
    Nagaroor 
    Nanniyode 
    Navaikulam 
    Nellanad 
    Ottasekharamangalam 
    Ottoor 
    Pallichal 
    Pallickal 
    Panavoor 
    Pangode 
    Parassala 
    Pazhayakunnumel 
    Peringammala 
    Perumkadavila 
    Poovachal 
    Poovar 
    Pothencode 
    Pulimath 
    Pullampara 
    Thirupuram 
    Tholicode 
    Uzhamalakkal 
    Vakkom 
    Vamanapuram 
    Vellanad 
    Vellarada 
    Vembayam 
    Venganoor 
    Vettoor 
    Vilappil 
    Vilavoorkal 
    Vithura
    Thiruvananthapuram Corporation
    Kollam Corporation
    Cochin Corporation
    Thrissur Corporation
    Kozhikode Corporation
    Kannur Corporation
    Kanhangad 
    Kasaragod 
    Nileshwar 
    Anthoor 
    Iritty 
    Kuthuparamba 
    Mattanur 
    Panoor 
    Payyannur 
    Sreekandapuram 
    Thalassery 
    Thalipparamba 
    Kalpetta 
    Mananthavady 
    Sulthan Bathery 
    Feroke 
    Koduvally 
    Koyilandy 
    Mukkam 
    Payyoli 
    Ramanattukara 
    Vadakara 
    Kondotty 
    Kottakkal 
    Malappuram 
    Manjeri 
    Nilambur 
    Parappanangadi 
    Perinthalmanna 
    Ponnani 
    Tanur 
    Tirur 
    Tirurangadi 
    Valanchery 
    Cherpulassery 
    Chittur Tattamangalam 
    Mannarkad 
    Ottapalam 
    Palakkad 
    Pattambi 
    Shoranur 
    Chalakudy 
    Chavakkad 
    Guruvayur 
    Irinjalakuda 
    Kodungallur 
    Kunnamkulam 
    Wadakanchery 
    Aluva 
    Angamaly 
    Eloor 
    Kalamassery 
    Koothattukulam 
    Kothamangalam 
    Maradu 
    Muvattupuzha 
    North Paravur 
    Perumbavoor 
    Piravom 
    Thrikkakara 
    Tripunithura 
    Kattappana 
    Thodupuzha 
    Changanassery 
    Erattupetta 
    Ettumanoor 
    Kottayam 
    Pala 
    Vaikom 
    Changanassery 
    Erattupetta 
    Ettumanoor 
    Kottayam 
    Pala 
    Vaikom 
    Adoor 
    Pandalam 
    Pathanamthitta 
    Thiruvalla 
    Karunagappally 
    Kottarakara 
    Paravur 
    Punalur 
    Attingal 
    Nedumangad 
    Neyyattinkara 
    Varkala
    Athiyannoor 
    Chirayinkeezhu 
    Kazhakuttom 
    Kilimanoor 
    Nedumangad 
    Nemom 
    Parassala 
    Perumkadavila 
    Vamanapuram 
    Varkala 
    Vellanad 
    Anchal 
    Chadayamangalam 
    Chavara 
    Chittumala 
    Ithikkara 
    Kottarakara 
    Mukhathala 
    Oachira 
    Pathanapuram
    Sasthamcotta 
    Vettikavala 
    Elanthoor 
    Koipuram 
    Konni 
    Mallappally 
    Pandalam 
    Parakkode 
    Pulikeezhu 
    Ranni 
    Ambalapuzha 
    Aryad 
    Bharanickavu 
    Champakulam 
    Chengannur 
    Haripad 
    Kanjikuzhy 
    Mavelikara 
    Muthukulam 
    Pattanakkad 
    Thycattussery 
    Veliyanad 
    Erattupetta 
    Ettumanoor 
    Kaduthuruthy 
    Kanjirappally 
    Lalam 
    Madappally 
    Pallom 
    Pampady 
    Uzhavoor 
    Vaikom 
    Vazhoor 
    Adimaly 
    Azhutha 
    Devikulam 
    Elemdesam 
    Idukki 
    Kattappana 
    Nedumkandam 
    Thodupuzha 
    Alangad 
    Angamaly 
    Edappally 
    Koovappady 
    Kothamangalam 
    Mulanthuruthy 
    Muvattupuzha 
    Palluruthy 
    Pampakuda 
    Parakkadavu 
    Paravur
    Vadavucode 
    Vazhakulam 
    Vypin 
    Anthikad 
    Chalakudy 
    Chavakkad 
    Cherpu 
    Chowannur 
    Irinjalakuda 
    Kodakara 
    Mala 
    Mathilakam 
    Mullassery 
    Ollukkara 
    Pazhayannur 
    Puzhakkal 
    Thalikulam 
    Vellangallur 
    Wadakanchery 
    Alathur 
    Attappady 
    Chittur 
    Kollengode 
    Kuzhalmannam 
    Malampuzha 
    Mannarkkad 
    Nenmara 
    Ottapalam 
    Palakkad 
    Pattambi 
    Sreekrishnapuram 
    Trithala 
    Areacode 
    Kalikavu 
    Kondotty 
    Kuttippuram 
    Malappuram 
    Mankada 
    Nilambur 
    Perinthalmanna 
    Perumpadappa 
    Ponnani 
    Tanur 
    Tirur 
    Tirurangadi 
    Vengara 
    Wandoor 
    Balussery 
    Chelannur 
    Koduvally 
    Kozhikode 
    Kunnamangalam 
    Kunnummal 
    Melady 
    Panthalayani 
    Perambra 
    Thodannur 
    Tuneri 
    Vadakara 
    Kalpetta 
    Mananthavady 
    Panamaram 
    Sulthan Bathery 
    Edakkad 
    Irikkur 
    Iritty 
    Kalliasseri 
    Kannur 
    Kuthuparamba 
    Panoor 
    Payyannur 
    Peravoor 
    Thalassery 
    Thalipparamba 
    Kanhangad 
    Karadka 
    Kasaragod 
    Manjeshwar 
    Nileshwar 
    Parappa 
    Kasaragod District Panchayat
    Kannur District Panchayat
    Wayanad District Panchayat
    Kozhikode District Panchayat
    Malappuram District Panchayat
    Palakkad District Panchayat
    Thrissur District Panchayat
    Ernakulam District Panchayat
    Idukki District Panchayat
    Kottayam District Panchayat
    Alappuzha District Panchayat
    Pathanamthitta District Panchayat
    Kollam District Panchayat
    Thiruvananthapuram District Panchayat
  }
end
